create table if not exists users
(
    id    bigint generated by default as identity not null,
    name  varchar(255)                            not null,
    email varchar(255)                            not null,
    constraint pk_user primary key (id),
    constraint uq_user_email unique (email)
);

create table if not exists items
(
    id          bigint generated by default as identity not null,
    name        varchar(255)                            not null,
    description varchar(255)                            not null,
    is_available   boolean                                 not null,
    owner_id    bigint                                  not null,
    constraint pk_item primary key (id),
    constraint fk_item_owner_id foreign key (owner_id) references users (id)
);

create table if not exists bookings
(
    id         bigint generated by default as identity not null,
    start_date timestamp without time zone             not null,
    end_date   timestamp without time zone             not null,
    status     varchar(20)                             default 'WAITING',
    item_id    bigint                                  not null,
    booker_id  bigint                                  not null,
    constraint pk_booking primary key (id),
    constraint fk_booking_item_id foreign key (item_id) references items (id),
    constraint fk_booking_booker_id foreign key (booker_id) references users (id)
);


create table if not exists comments
(
    id        bigint generated by default as identity not null,
    created   timestamp without time zone,
    text      varchar(255)                            not null,
    author_id bigint                                  not null,
    item_id   bigint                                  not null,
    constraint pk_comment primary key (id),
    constraint fk_comment_item_id foreign key (item_id) references items (id),
    constraint fk_comment_author_id foreign key (author_id) references users (id)
)

